### ISSUE TITLE
bansync

### ISSUE THREAD

**Issue by fungreenfox** [CraftMinecraft/BanSync#9]
Only bansync removeuser <name> workds. Nothing automaticly does anything here.
From ingame, it seems quite ok, but claims are not being removed regarding Griefprevention.
Working from the console, we get this:

> bansync removeuser ghk128
> 06:11:19 [INFO] [BanSync] [INFO] CONSOLE send command /bansync removeuser ghk128
> 06:11:19 [INFO] [BanSync] [INFO] Removing LWC Locks
> 06:11:19 [INFO] Loading protections via STREAM mode
> 06:11:19 [INFO] 1 / 25812
> 06:11:19 [SEVERE] java.sql.SQLException: Streaming result set com.mysql.jdbc.RowDataDynamic@2c149513 is still active. No statements may be issued when any streaming result sets are open and in use on a giv
> en connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
> 06:11:19 [SEVERE]       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:934)
> 06:11:19 [SEVERE]       at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:931)
> 06:11:19 [SEVERE]       at com.mysql.jdbc.MysqlIO.checkForOutstandingStreamingData(MysqlIO.java:2724)
> 06:11:19 [SEVERE]       at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1895)
> 06:11:19 [SEVERE]       at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
> 06:11:19 [SEVERE]       at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
> 06:11:19 [SEVERE]       at com.mysql.jdbc.ConnectionImpl.setAutoCommit(ConnectionImpl.java:5022)
> 06:11:19 [SEVERE]       at com.griefcraft.sql.Database.setAutoCommit(Database.java:158)
> 06:11:19 [SEVERE]       at com.griefcraft.util.DatabaseThread.flushDatabase(DatabaseThread.java:127)
> 06:11:19 [SEVERE]       at com.griefcraft.util.DatabaseThread.run(DatabaseThread.java:157)
> 06:11:19 [SEVERE]       at java.lang.Thread.run(Unknown Source)
> 06:11:19 [INFO] REMOVED 4 / 4
> 06:11:19 [INFO] [BanSync] [INFO] Removing Players Economy
> 06:11:19 [INFO] [BanSync] [Debug] Player had a balance of: 163.0
> 06:11:19 [INFO] [BanSync] [INFO] Removing Claims from Grief Prevention
> 06:11:19 [INFO] [BanSync] ghk128 has been cleared

Updating to latest dev build of bansync works better. Thumb up :)
But still no removal of a GP claim takes place.
Btw: We are using serubans, can bansync work with this?

**Comment by roblabla** [comment]
WAH, I just looked at serubans, this plugin is badly designed ! Not only it doesn't even set the player as banned (which is already a downright huge design flaw), but it doesn't even fire bukkit's PlayerBanEvent. As such, we have no way of knowing if a player is banned if he is banned through this plugin.

**Comment by FireBall1725** [comment]
Thanks for the bug report, The error above looks like i need to find a new way to remove LWC protections.  As for GP not working correctly, I am not sure to the reason why.  I will do more testing and attempt to fix this issue.

As for the serubans, i guess from why my partner is saying it dosn't ban the typical way, i will keep an eye on their project and there might be a way to hook it in the future.

**Comment by fungreenfox** [comment]
Bad programming. I am so happy for serubans, but they deliver their own ban command, i think.
The big deal is the webinterface, giving a quick overview of banned players, and possebility to edit it online.
If he is your partner, can you convince him to wamp his code up?

**Comment by fungreenfox** [comment]
I remember, once upon a time (not in the west :P), maybe half a year ago, we had to unban players by using pardon, not "unban". I think this got corrected later.

**Comment by roblabla** [comment]
On a second look, we could support it, in a way. It'll just need a special treatment. So spoiled.

**Comment by fungreenfox** [comment]
I would be very happy :)

**Comment by fungreenfox** [comment]
hmm.. a version looking into the mysql db for banned players.. just a thought..
